#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
name: CI
# Trigger the workflow on push
on:
  push:
jobs:
  docker-build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: quay.io/eclipse/che-dashboard
    steps:
    - uses: actions/checkout@v2
      name: Checkout che-dashboard source code
    - name: Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v1.5.0
      with:
        version: v0.4.1
    - name: "Docker Login"
      run:  docker login -u "${{ secrets.QUAY_USERNAME }}" -p "${{ secrets.QUAY_PASSWORD }}" quay.io
    - name: "Docker build"
      run: |
        docker image prune -a -f
        IMAGE_WITH_TAG=${IMAGE_NAME}:next
        docker buildx build --cache-from="type=registry,ref=${IMAGE_WITH_TAG}" --cache-to="type=registry,ref=${IMAGE_WITH_TAG},mode=max" --platform "linux/amd64" -t ${IMAGE_WITH_TAG} -f Dockerfile.apache .
    - name: "Docker Logout"
      run: docker logout
